apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-deployment
  labels:
    app: healthcare
spec:
  replicas: 1
  selector:
    matchLabels:
      app: healthcare
  template:
    metadata:
      labels:
        app: healthcare
    spec:
      containers:
      - name: healthcare
        image: pavanputtur/healthcare:1.0
        ports:
        - containerPort: 8080




---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-svc
spec:
  selector:
     app: healthcare
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30070


