---
- name : Configure Docker on New Prod-Server-EC2 Instances
  hosts : all
  become: true
  tasks :
  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root
  - name : Deploy the image and Run as a Container
    command : docker run -itd -p 8086:8082 pavanputtur/healthcare:1.0
  - name : Deploying Container on kubernetes
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: healthcare-deployment
      labels:
        app: healthcare
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: healthcare
      template:
        metadata:
          labels:
            app: healthcare
        spec:
          containers:
          - name: healthcare
            image: pavanputtur/healthcare:1.0
            ports:
            - containerPort: 8040
  - name : creating service
    apiVersion: v1
    kind: Service
    metadata:
      name: healthcare-service
    spec:
      selector:
        app: healthcare
      type: NodePort
      ports:
        - protocol: TCP
          port: 80
          targetPort: 8080
          nodePort: 30010
