---
- name : Configure Docker on New Prod-Server-EC2 Instances
  hosts : all
  become: true
  tasks :
  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root
  - name : Deploy the image and Run as a Container
    command : docker run -itd -p 8084:8082 pavanputtur/healthcare:1.0
